# Generated by Django 5.2.7 on 2025-10-31 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MitraProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('operational_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_orders', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitra Profile',
                'verbose_name_plural': 'Mitra Profiles',
                'db_table': 'mitra_profiles',
            },
        ),
        migrations.CreateModel(
            name='MitraRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('operational_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitra Request',
                'verbose_name_plural': 'Mitra Requests',
                'db_table': 'mitra_requests',
            },
        ),
    ]
