# Generated by Django 5.2.7 on 2025-11-01 02:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CODRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Jarak Min (KM)')),
                ('max_distance_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Jarak Max (KM)')),
                ('fee', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Biaya COD')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'COD Rate',
                'verbose_name_plural': 'COD Rates',
                'db_table': 'cod_rates',
                'ordering': ['min_distance_km'],
            },
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Laundry')),
                ('address', models.TextField(verbose_name='Alamat Lengkap')),
                ('district', models.CharField(default='Yogyakarta', max_length=100, verbose_name='Kecamatan')),
                ('city', models.CharField(default='Yogyakarta', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_per_kg', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Harga per KG')),
                ('min_order_kg', models.DecimalField(decimal_places=1, default=2.0, max_digits=5, verbose_name='Min Order (KG)')),
                ('operating_hours_start', models.TimeField(default='08:00')),
                ('operating_hours_end', models.TimeField(default='20:00')),
                ('estimated_pickup_time', models.IntegerField(default=60, verbose_name='Estimasi Waktu Jemput (menit)')),
                ('estimated_delivery_time', models.IntegerField(default=1440, verbose_name='Estimasi Pengiriman (menit)')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_orders_completed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_open_now', models.BooleanField(default=True)),
                ('has_regular_wash', models.BooleanField(default=True, verbose_name='Cuci Setrika')),
                ('has_dry_clean', models.BooleanField(default=True, verbose_name='Dry Clean')),
                ('has_express', models.BooleanField(default=True, verbose_name='Express')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundries', to='partners.mitraprofile')),
            ],
            options={
                'verbose_name': 'Laundry',
                'verbose_name_plural': 'Laundries',
                'db_table': 'laundries',
                'ordering': ['-rating', '-total_orders_completed'],
            },
        ),
    ]
