# Generated by Django 5.2.7 on 2025-11-01 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_codrate_laundry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='map_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Google Maps'),
        ),
        migrations.CreateModel(
            name='LaundryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='laundry_images/%Y/%m/', verbose_name='Gambar')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Gambar Utama')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partners.laundry')),
            ],
            options={
                'verbose_name': 'Laundry Image',
                'verbose_name_plural': 'Laundry Images',
                'db_table': 'laundry_images',
                'ordering': ['order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Voucher')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Voucher')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('voucher_type', models.CharField(choices=[('free_shipping', 'Free Ongkir'), ('percentage_discount', 'Diskon Persentase'), ('fixed_discount', 'Diskon Nominal'), ('free_kg', 'Gratis KG')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Persentase (1-100) atau Nominal (Rupiah) atau KG', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, help_text='Maksimal diskon untuk persentase', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Min Pembelian (Rp)')),
                ('min_order_kg', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Min Order (KG)')),
                ('max_usage_per_user', models.IntegerField(default=1, verbose_name='Max Pemakaian per User')),
                ('total_quota', models.IntegerField(default=100, verbose_name='Total Kuota')),
                ('used_count', models.IntegerField(default=0, verbose_name='Sudah Dipakai')),
                ('valid_from', models.DateTimeField(verbose_name='Berlaku Dari')),
                ('valid_until', models.DateTimeField(verbose_name='Berlaku Sampai')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Disetujui Admin')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='partners.laundry')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'db_table': 'vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('free_shipping', 'Free Ongkir'), ('percentage_discount', 'Diskon Persentase'), ('fixed_discount', 'Diskon Nominal'), ('free_kg', 'Gratis KG')], max_length=20)),
                ('voucher_name', models.CharField(max_length=200)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_kg', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('total_quota', models.IntegerField(default=100)),
                ('duration_days', models.IntegerField(default=30, verbose_name='Durasi (Hari)')),
                ('reason', models.TextField(verbose_name='Alasan Pengajuan')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Admin')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_origin', to='partners.voucher')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_requests', to='partners.laundry')),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_requests', to='partners.mitraprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_voucher_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher Request',
                'verbose_name_plural': 'Voucher Requests',
                'db_table': 'voucher_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
