# Generated by Django 5.2.7 on 2025-11-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_laundry_map_link_laundryimage_voucher_voucherrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='status',
            field=models.CharField(choices=[('buka', 'Buka'), ('full', 'Full Booked'), ('istirahat', 'Istirahat'), ('tutup', 'Tutup')], default='buka', max_length=10, verbose_name='Status'),
        ),
    ]
