# Generated by Django 5.2.7 on 2025-11-01 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_laundry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MitraVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap (sesuai KTP)')),
                ('ktp_number', models.CharField(max_length=16, verbose_name='Nomor KTP')),
                ('ktp_image', models.ImageField(upload_to='mitra_verifications/ktp/', verbose_name='Foto KTP')),
                ('selfie_with_ktp', models.ImageField(upload_to='mitra_verifications/selfie/', verbose_name='Foto Selfie dengan KTP')),
                ('business_name', models.CharField(max_length=200, verbose_name='Nama Usaha Laundry')),
                ('business_address', models.TextField(verbose_name='Alamat Usaha')),
                ('business_phone', models.CharField(max_length=15, verbose_name='Nomor Telepon Usaha')),
                ('store_front_photo', models.ImageField(upload_to='mitra_verifications/business/', verbose_name='Foto Depan Toko')),
                ('store_interior_photo', models.ImageField(upload_to='mitra_verifications/business/', verbose_name='Foto Interior Toko')),
                ('equipment_photo', models.ImageField(blank=True, null=True, upload_to='mitra_verifications/business/', verbose_name='Foto Peralatan Laundry')),
                ('bank_name', models.CharField(choices=[('bri', 'Bank BRI'), ('bca', 'Bank BCA'), ('mandiri', 'Bank Mandiri'), ('bni', 'Bank BNI'), ('seabank', 'SeaBank'), ('other', 'Lainnya')], max_length=20, verbose_name='Nama Bank')),
                ('bank_account_number', models.CharField(max_length=20, verbose_name='Nomor Rekening')),
                ('bank_account_name', models.CharField(max_length=200, verbose_name='Nama Pemilik Rekening')),
                ('bank_account_proof', models.ImageField(upload_to='mitra_verifications/bank/', verbose_name='Foto Buku Tabungan/Bukti Rekening')),
                ('years_of_experience', models.IntegerField(default=0, verbose_name='Pengalaman (Tahun)')),
                ('daily_capacity_kg', models.DecimalField(decimal_places=1, default=50.0, max_digits=6, verbose_name='Kapasitas Harian (KG)')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status Verifikasi')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Verifikasi')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Admin')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Submit')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Waktu Update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_verification', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_mitras', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi Oleh')),
            ],
            options={
                'verbose_name': 'Mitra Verification',
                'verbose_name_plural': 'Mitra Verifications',
                'db_table': 'mitra_verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
