# Generated by Django 5.2.7 on 2025-11-01 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment'),
        ('partners', '0005_mitraverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MitraTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Total Pembayaran Pelanggan')),
                ('platform_fee', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Fee Platform (3%)')),
                ('mitra_earning', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Pendapatan Mitra')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Tujuan')),
                ('bank_account_number', models.CharField(max_length=20, verbose_name='No. Rekening')),
                ('bank_account_name', models.CharField(max_length=200, verbose_name='Nama Pemilik Rekening')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Transfer'), ('processing', 'Sedang Diproses'), ('completed', 'Transfer Selesai'), ('failed', 'Transfer Gagal')], default='pending', max_length=20, verbose_name='Status Transfer')),
                ('transfer_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referensi Transfer')),
                ('transfer_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Transfer')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Proses')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Terakhir')),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='partners.mitraprofile', verbose_name='Mitra')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mitra_transaction', to='orders.order', verbose_name='Order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Diproses Oleh')),
            ],
            options={
                'verbose_name': 'Mitra Transaction',
                'verbose_name_plural': 'Mitra Transactions',
                'db_table': 'mitra_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
