# Generated by Django 5.2.7 on 2025-11-01 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_mitratransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
