# Generated by Django 5.2.7 on 2025-11-01 02:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('partners', '0002_codrate_laundry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='actual_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Antar Aktual'),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Biaya COD'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Alamat Pengantaran'),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Jarak (KM)'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimasi Selesai'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='laundry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='partners.laundry'),
        ),
        migrations.AddField(
            model_name='order',
            name='laundry_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Harga Laundry'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Fee Platform'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.5)], verbose_name='Berat (KG)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(verbose_name='Alamat Penjemputan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(verbose_name='Waktu Jemput'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Total Harga'),
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Aksi')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='orders.order')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'db_table': 'transaction_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
