# Generated by Django 5.2.7 on 2025-11-01 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_delivery_time_remove_order_quantity_and_more'),
        ('partners', '0003_laundry_map_link_laundryimage_voucher_voucherrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='partners.voucher', verbose_name='Voucher Digunakan'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Diskon dari Voucher'),
        ),
    ]
