# Generated by Django 5.2.7 on 2025-11-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_voucher_order_voucher_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Bukti Pembayaran'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('qris', 'QRIS / QR Code'), ('bri', 'Bank BRI'), ('bca', 'Bank BCA'), ('seabank', 'SeaBank'), ('shopee', 'ShopeePay')], default='cod', max_length=20),
        ),
    ]
