# Generated by Django 5.2.7 on 2025-11-01 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='No. Tiket')),
                ('issue_type', models.CharField(choices=[('payment_failed', 'Pembayaran Gagal'), ('wrong_amount', 'Nominal Salah'), ('not_verified', 'Belum Diverifikasi'), ('refund_request', 'Permintaan Refund'), ('other', 'Lainnya')], max_length=30, verbose_name='Jenis Kendala')),
                ('subject', models.CharField(max_length=200, verbose_name='Subjek')),
                ('description', models.TextField(verbose_name='Deskripsi Masalah')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payment_issues/', verbose_name='Screenshot/Bukti')),
                ('status', models.CharField(choices=[('open', 'Baru'), ('in_progress', 'Sedang Ditangani'), ('resolved', 'Selesai'), ('closed', 'Ditutup')], default='open', max_length=20, verbose_name='Status')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Tanggapan Admin')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Tanggapan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_issues', to='orders.order', verbose_name='Order')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL, verbose_name='Ditangani Oleh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_issues', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment Issue',
                'verbose_name_plural': 'Payment Issues',
                'db_table': 'payment_issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
