# Generated by Django 5.2.7 on 2025-11-01 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_paymentissue'),
        ('partners', '0006_mitratransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating 1-5 bintang', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(help_text='Berikan ulasan Anda', verbose_name='Komentar')),
                ('service_quality', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Kualitas Layanan')),
                ('cleanliness', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Kebersihan')),
                ('speed', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Kecepatan')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Foto 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Foto 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Foto 3')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Disetujui')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ditampilkan di Highlight')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate')),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='partners.laundry', verbose_name='Laundry')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
